# -*- coding: utf-8 -*-
import stat
import subprocess
from pathlib import Path

from rich.console import Console

console = Console()

HOOK_MAGIC = "# lazy-commit hook v1"

PREPARE_COMMIT_MSG_HOOK = """#!/bin/sh
# lazy-commit hook v1
# Auto-generated by lazy-commit - do not edit manually

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# Only run for normal commits (not merge, squash, etc.)
if [ -z "$COMMIT_SOURCE" ]; then
    # Check if there are staged changes
    if ! git diff --cached --quiet; then
        # Generate commit message with lazy-commit
        GENERATED_MSG=$(commit --hook-mode 2>/dev/null)
        
        if [ $? -eq 0 ] && [ -n "$GENERATED_MSG" ]; then
            echo "$GENERATED_MSG" > "$COMMIT_MSG_FILE"
        fi
    fi
fi

exit 0
"""


class HookManager:
    def __init__(self):
        self.repo_path = self._find_git_root()
        self.hooks_dir = self.repo_path / ".git" / "hooks"

    @staticmethod
    def _find_git_root() -> Path:
        try:
            git_root_str = subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                text=True,
                stderr=subprocess.PIPE,
                cwd=Path.cwd(),
            ).strip()
            return Path(git_root_str)
        except (subprocess.CalledProcessError, FileNotFoundError):
            console.print(
                "[red]Fatal: Not a git repository (or any of the parent directories).[/red]"
            )
            raise ValueError("This script must be run from within a Git repository.")

    def _is_our_hook(self, hook_path: Path) -> bool:
        if not hook_path.exists():
            return False
        with open(hook_path, "r", encoding="utf-8") as f:
            content = f.read()
        return HOOK_MAGIC in content

    def install(
        self, hook_type: str = "prepare-commit-msg", force: bool = False
    ) -> bool:
        console.print(f"[bold blue]Installing {hook_type} hook...[/bold blue]")

        if not self.hooks_dir.exists():
            self.hooks_dir.mkdir(parents=True, exist_ok=True)

        hook_path = self.hooks_dir / hook_type

        if hook_path.exists():
            if self._is_our_hook(hook_path):
                console.print(f"[yellow]Hook already installed at {hook_path}[/yellow]")
                return True
            elif not force:
                console.print(
                    f"[red]Hook already exists at {hook_path}[/red]\n"
                    "[dim]Use --force to overwrite[/dim]"
                )
                return False
            else:
                backup_path = hook_path.with_suffix(".backup")
                hook_path.rename(backup_path)
                console.print(f"[dim]Backed up existing hook to {backup_path}[/dim]")

        if hook_type == "prepare-commit-msg":
            hook_content = PREPARE_COMMIT_MSG_HOOK
        else:
            console.print(f"[red]Unsupported hook type: {hook_type}[/red]")
            return False

        with open(hook_path, "w", encoding="utf-8") as f:
            f.write(hook_content)

        hook_path.chmod(
            hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
        )

        console.print(f"[green]Hook installed successfully at {hook_path}[/green]")
        return True

    def uninstall(self, hook_type: str = "prepare-commit-msg") -> bool:
        console.print(f"[bold blue]Uninstalling {hook_type} hook...[/bold blue]")

        hook_path = self.hooks_dir / hook_type

        if not hook_path.exists():
            console.print(f"[yellow]No hook found at {hook_path}[/yellow]")
            return True

        if not self._is_our_hook(hook_path):
            console.print(
                f"[red]Hook at {hook_path} was not created by lazy-commit[/red]\n"
                "[dim]Refusing to remove to avoid data loss[/dim]"
            )
            return False

        hook_path.unlink()
        console.print("[green]Hook removed successfully[/green]")

        backup_path = hook_path.with_suffix(".backup")
        if backup_path.exists():
            backup_path.rename(hook_path)
            console.print(f"[dim]Restored backup hook from {backup_path}[/dim]")

        return True

    def status(self, hook_type: str = "prepare-commit-msg") -> None:
        console.print(f"[bold blue]Hook status for {hook_type}:[/bold blue]")

        hook_path = self.hooks_dir / hook_type

        if not hook_path.exists():
            console.print("[yellow]Not installed[/yellow]")
            return

        if self._is_our_hook(hook_path):
            console.print(f"[green]Installed[/green] at {hook_path}")
        else:
            console.print(
                f"[yellow]External hook exists[/yellow] at {hook_path}\n"
                "[dim]This hook was not created by lazy-commit[/dim]"
            )
